# Generated by Django 5.2.9 on 2026-03-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bvn_number',
            field=models.CharField(blank=True, help_text='Bank Verification Number (11 digits)', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bvn_verified',
            field=models.BooleanField(default=False, help_text='Whether BVN has been verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='bvn_verified_at',
            field=models.DateTimeField(blank=True, help_text='When BVN was verified', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp',
            field=models.CharField(blank=True, help_text='Current OTP for phone verification', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp_created_at',
            field=models.DateTimeField(blank=True, help_text='When OTP was generated', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='When OTP expires (10 minutes)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Whether phone number has been verified via OTP'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='When phone was verified', null=True),
        ),
    ]
