# Generated by Django 5.2.9 on 2025-12-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='store_name',
            field=models.CharField(blank=True, help_text="Store name (optional). Defaults to '{First Name}'s Store' if not provided", max_length=255, null=True),
        ),
    ]
