# Generated by Django 5.2.9 on 2026-03-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bvn_number_user_bvn_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_otp_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_otp_expires_at',
        ),
        migrations.AddField(
            model_name='user',
            name='kudisms_verification_id',
            field=models.CharField(blank=True, help_text='verification_id returned by Kudisms sendotp API', max_length=255, null=True),
        ),
    ]
