# Generated by Django 5.2.9 on 2025-12-07 15:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=50000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_balance', models.DecimalField(decimal_places=2, default=50000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_credit_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loan_status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Exhausted'), ('REPAID', 'Repaid'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_repayment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'BUYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditLimitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_history', to='credits.creditaccount')),
                ('increased_by', models.ForeignKey(help_text='Admin who approved the increase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_credit_increases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Credit limit histories',
                'db_table': 'credit_limit_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('REPAYMENT', 'Repayment'), ('LIMIT_INCREASE', 'Limit Increase'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credits.creditaccount')),
            ],
            options={
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_history', to='credits.creditaccount')),
                ('repaid_by', models.ForeignKey(help_text='Admin who processed the repayment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_repayments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Repayment histories',
                'db_table': 'repayment_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['user'], name='credit_acco_user_id_c8efa7_idx'),
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['loan_status'], name='credit_acco_loan_st_29c021_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['credit_account', '-created_at'], name='credit_tran_credit__8ea465_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['transaction_type'], name='credit_tran_transac_0eee54_idx'),
        ),
    ]
